const Constants = {
    login: "LOGIN",
    registration:"REGISTER",
    studentinfo:"Student Info",
    contactInfo:"Contact",
    password:"Password",
    forgetPassword:"Forget Password?",
    DonothaveAccount:"Don't have an Account?",
    alredyHaveAnAccount:"Already have an Account?",
    signup:"Sign Up",
    loginNow:"Login Now",
    continue:"CONTINUE",
    otpHeader:"Enter OTP Received In Your Email To Verify",
    verify:"VERIFY",
    resendCode:"Resend Code",
    cbtTryOut:"CBT Tryout",
    Agcu:"AGCU",
    Asm:"ASM",
    selectedPackages:"Your Selected Package",
    token:"",
    levelArray:[],
    classArray:[],
    stateArray:[],
    cityArray:[],
    schoolArray:[],
    selectedAns: [],
    quesIndex:0,
    ansIndex:0,
    durasiValue:0,
    timeLeft:0,
    isAnswered: false,
}

export default Constants;