const Images = {
    emailIcon:require("../assets/images/email.png"),
    lockIcon:require("../assets/images/lock.png"),
    eyeIcon:require("../assets/images/eye.png"),
    userNameIcon:require("../assets/images/userNameIcon.png"),
    fullNameIcon:require("../assets/images/fullNameIcon.png"),
    phoneIcon:require("../assets/images/phoneIcon.png"),
    levelIcon:require("../assets/images/levelIcon.png"),
    classIcon:require("../assets/images/classIcon.png"),
    dropdownIcon:require("../assets/images/downArrowIcon.png"),
    resendIcon:require("../assets/images/resendIcon.png"),
    programsIcon:require("../assets/images/programsIcon.png"),
    examsIcon:require("../assets/images/examsIcon.png"),
    homeworksIcon:require("../assets/images/homeworkIcon.png"),
    createdExamsIcon:require("../assets/images/createdExamsIcon.png"),
    dasboardShadow:require("../assets/images/dashboardShadow.png"),
    searchIcon:require("../assets/images/searchIcon.png"),
    filterIcon:require("../assets/images/filterIcon.png"),
    programsUserIcon:require("../assets/images/userIcon.png"),
    programsCalendarIcon:require("../assets/images/calendarIcon.png"),
    cardUpArrowIcon:require("../assets/images/upArrowIcon.png"),
    cardDownArrowIcon:require("../assets/images/downArrow.png"),
    theme1SideArrowIcon:require("../assets/images/theme1SideArrowIcon.png"),
    theme2SideArrowIcon:require("../assets/images/theme2SideArrowIcon.png"),
    theme3SideArrowIcon:require("../assets/images/theme3SideArrowIcon.png"),
    playIcon:require("../assets/images/playIcon.png"),
    backIcon:require("../assets/images/backButtonIcon.png"),
    examImage:require("../assets/images/examImage.png"),
    playIcon:require("../assets/images/playIcon.png"),
    checkIcon: require("../assets/images/Profile/tick.png"),
    closeIcon: require("../assets/images/Profile/close.png"),
}

export default Images;